### ISSUE TITLE
Thank you so much bro :(

### ISSUE THREAD

**Issue by vietdot** [TeamWin/android_device_xiaomi_fire#1]

**Comment by LandMA07** [comment]
it bricked my phone
it keeps rebooting to twrp
even shutdown not working

**Comment by vietdot** [comment]
poor

Vào 13:16, Th 2, 29 thg 4, 2024 LandMA07 ***@***.***> đã viết:

**Comment by AntarcticShaurant** [comment]
> it bricked my phone it keeps rebooting to twrp even shutdown is not working

#2 Let's move here since you opened the issue

**Comment by AntarcticShaurant** [comment]
by the way, please close the issue if you don't have anything else to add @vietdot
