### ISSUE TITLE
[BUG] my phone can't exist TWRP

### ISSUE THREAD

**Issue by Lando0007** [TeamWin/android_device_xiaomi_fire#2]
my phone keeps rebooting to twrp if I want to boot to system or to shutdown it

**Comment by AntarcticShaurant** [comment]
What steps did you follow to flash it?

Edit: Usually this happens when you don't flash stock boot.

**Comment by vietdot** [comment]
> What steps did you follow to flash it?
> 
> Edit: Usually this happens when you don't flash stock boot.

how to flash stock boot ?

**Comment by AntarcticShaurant** [comment]
> > What steps did you follow to flash it?
> > Edit: Usually this happens when you don't flash stock boot.
> 
> how to flash stock boot ?

`fastboot flash boot boot.img`

Also what i meant is that you need to flash stock boot, and then inject it to ramdisk, and not just flashing recovery.

That's why i asked them to tell me what steps they followed.

**Comment by Lando0007** [comment]
I just flashed the twrp image

**Comment by Lando0007** [comment]
anyways
I fixed it
I just flashed the magisk patched boot.img
then I installed twrp with the .zip file and it's working now
